name: Deploy Staging
on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i

      - name: Build
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
          NODE_ENV: 'development'
          VERSION: ${{ github.ref_name }}
        run: bun run build

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy ./.svelte-kit/cloudflare --project-name=${{ secrets.CLOUDFLARE_PAGES_STAGING_PROJECT_NAME }} --branch=main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
